name: Build Custom Ubuntu 26.04 Rootfs

on:
  workflow_dispatch: # Allows you to trigger the build manually with a single click button

jobs:
  build-archive:
    runs-on: ubuntu-26.04-arm
    steps:
      - name: Checkout Repository Files
        uses: actions/checkout@v4

      - name: Install Generation Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y mmdebstrap xz-utils

      - name: Compile and Compress Ubuntu 26.04 Rootfs
        run: |
          sudo mmdebstrap --variant=minbase plucky ./ubuntu-26.04-rootfs.tar.xz "http://ports.ubuntu.com"

      - name: Upload Finished Rootfs File Package
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-26.04-arm64-rootfs
          path: ./ubuntu-26.04-rootfs.tar.xz
          compression-level: 0 # File is already compressed with high-efficiency xz
